services:
  app:
    build: .
    container_name: php-validation-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - 9000:9000
    depends_on:
      - db
    entrypoint: ["sh", "-c", "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache && php-fpm"]
    networks:
      - laravel-network
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 log=/var/log/xdebug.log start_with_request=yes
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8.0
    container_name: php-validation-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - laravel-network

volumes:
  db_data:

networks:
  laravel-network:
    driver: bridge
